### PR TITLE
feat: add github logo in storybook

### PR DESCRIPTION
**Pull request by nmerget**

### CODE REVIEW

**Comment by mfranzke** [comment]
@nmerget please add a `packages/db-ui-elements-stencil/src/assets/GitHub-Mark-Light-32px.png.license` file that includes the license information for this image.

**Review by mfranzke — CHANGES_REQUESTED** [review]
@nmerget please add a packages/db-ui-elements-stencil/src/assets/GitHub-Mark-Light-32px.png.license file that includes the license information for this image.

**Comment by nmerget** [comment]
> @nmerget please add a packages/db-ui-elements-stencil/src/assets/GitHub-Mark-Light-32px.png.license file that includes the license information for this image.

fixed

**Review by nmerget — COMMENTED** [review]
fixed

**Review by mfranzke — APPROVED** [review]

**Pull request merged**
