### PR TITLE
fix: mainnavigation underneath 1024px viewports

### PR DESCRIPTION
**Pull request by mfranzke**
Resolves https://github.com/db-ui/elements/issues/1964

### CODE REVIEW

**Comment by mriehl** [comment]
any updates when this can be expected in a release?

**Comment by mfranzke** [comment]
@mriehl we'd like to both clean up as well as resolve a lot of open issues within the backlog by concentrated attention in January.

**Comment by mriehl** [comment]
> @mriehl we'd like to both clean up as well as resolve a lot of open issues within the backlog by concentrated attention in January.

uhm okay. I would have expected this issue to be higher priority, since any page using DB elements is completely unusable on a smaller viewport (if using a menu). But I guess if there are more important things it will have to wait.

It's quite difficult to explain to users who complain about the unusable navigation that I am using an official framework and it's simply broken upstream.

**Comment by mfranzke** [comment]
> > @mriehl we'd like to both clean up as well as resolve a lot of open issues within the backlog by concentrated attention in January.
> 
> uhm okay. I would have expected this issue to be higher priority, since any page using DB elements is completely unusable on a smaller viewport (if using a menu). But I guess if there are more important things it will have to wait.
> 
> It's quite difficult to explain to users who complain about the unusable navigation that I am using an official framework and it's simply broken upstream.

I actually don't know what kept us away from merging this earlier. Maybe there's still some outstanding features, but this should serve quite well as fix for the moment without breaking anything, but actually fixing the problem itself.

So I'll release this in the next half an hour.

**Comment by mriehl** [comment]
Thanks @mfranzke !

**Comment by mfranzke** [comment]
> Thanks @mfranzke !

thanks for your feedback & reportings.

**Pull request merged**
