### PR TITLE
refactor: added further information to the homepage

### PR DESCRIPTION
**Pull request by mfranzke**
listing all of the functionality and contents with our beautiful card component

### CODE REVIEW

**Comment by mfranzke** [comment]
@nmerget could you please add the *.license files for all of the images?

**Comment by mfranzke** [comment]
@nmerget for whatever reason, I'm not able to make the images work (still the incorrect/older file path). As you're the creator of this code, it might be easier for you to find the bug.

**Comment by nmerget** [comment]
> @nmerget could you please add the `*.license` files for all of the images?

> @nmerget for whatever reason, I'm not able to make the images work (still the incorrect/older file path). As you're the creator of this code, it might be easier for you to find the bug.

Both fixed

**Review by dkolba — APPROVED** [review]
LGTM

**Pull request merged**
