### PR TITLE
Add trufflehog to scan secrets

### PR DESCRIPTION
**Pull request by nmerget**

### CODE REVIEW

**Comment by mfranzke** [comment]
@nmerget What about scanning on pre-commit (additionally), as we might want to prevent any checkin of secrets prior to the commit itself?

**Comment by nmerget** [comment]
> @nmerget What about scanning on pre-commit (additionally), as we might want to prevent any checkin of secrets prior to the commit itself?

Do you have a suggestion? We should use a npm package for local pre-commit

**Comment by mfranzke** [comment]
> > @nmerget What about scanning on pre-commit (additionally), as we might want to prevent any checkin of secrets prior to the commit itself?
> 
> Do you have a suggestion? We should use a npm package for local pre-commit

sadly not :-(

**Comment by nmerget** [comment]
> > > @nmerget What about scanning on pre-commit (additionally), as we might want to prevent any checkin of secrets prior to the commit itself?
> > 
> > 
> > Do you have a suggestion? We should use a npm package for local pre-commit
> 
> sadly not :-(

All npm scanners are pretty old. Otherwise we would need docker to run some go/python scanner :(

**Comment by mfranzke** [comment]
> > > > @nmerget What about scanning on pre-commit (additionally), as we might want to prevent any checkin of secrets prior to the commit itself?
> > > 
> > > 
> > > Do you have a suggestion? We should use a npm package for local pre-commit
> > 
> > 
> > sadly not :-(
> 
> All npm scanners are pretty old. Otherwise we would need docker to run some go/python scanner :(

brew installation sounded feasible to me … at least for the Mac users … https://github.com/trufflesecurity/truffleHog#5-brew

**Comment by nmerget** [comment]
> > > > > @nmerget What about scanning on pre-commit (additionally), as we might want to prevent any checkin of secrets prior to the commit itself?
> > > > 
> > > > 
> > > > Do you have a suggestion? We should use a npm package for local pre-commit
> > > 
> > > 
> > > sadly not :-(
> > 
> > 
> > All npm scanners are pretty old. Otherwise we would need docker to run some go/python scanner :(
> 
> brew installation sounded feasible to me … at least for the Mac users … https://github.com/trufflesecurity/truffleHog#5-brew

I think this is not a solution. We should use only npm packages or bash inside pre-commit...

**Review by mfranzke — APPROVED** [review]

**Pull request merged**
